#!/bin/sh
## postinstall
## Installs Cloudstrike Falcon PKG from /tmp/ and registers license
## PKGed for X by WNETTO 2/21/20


sudo installer -verboseR -package "/private/tmp/FalconSensorMacOS.pkg" -target / && sudo /Library/CS/falconctl license XXX-XX

exit
